create table if not exists public.maintenance_activities (
  id bigint generated by default as identity primary key,
  title text not null,
  equipment text,
  description text,
  scheduled_date date not null,
  start_time time,
  end_time time,
  assigned_employee_id text,
  priority text not null default 'normal',
  recurrence_type text not null default 'none',
  recurrence_interval integer not null default 1,
  recurrence_end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint maintenance_recurrence_type_check check (recurrence_type in ('none','daily','weekly','monthly','yearly')),
  constraint maintenance_recurrence_interval_check check (recurrence_interval >= 1)
);

create table if not exists public.maintenance_completions (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.maintenance_activities(id) on delete cascade,
  occurrence_date date not null,
  completed_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  constraint maintenance_completion_unique unique (activity_id, occurrence_date)
);

create index if not exists maintenance_activities_date_idx on public.maintenance_activities(scheduled_date);
create index if not exists maintenance_completions_occurrence_idx on public.maintenance_completions(occurrence_date);

grant select, insert, update, delete on public.maintenance_activities to anon, authenticated, service_role;
grant select, insert, update, delete on public.maintenance_completions to anon, authenticated, service_role;
grant usage, select on sequence public.maintenance_activities_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.maintenance_completions_id_seq to anon, authenticated, service_role;

alter table public.maintenance_activities disable row level security;
alter table public.maintenance_completions disable row level security;

notify pgrst, 'reload schema';
